server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: core-championship
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pitstop_championship}
    username: ${SPRING_DATASOURCE_USERNAME:pitstop}
    password: ${SPRING_DATASOURCE_PASSWORD:pitstop_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
