-- Inicialização do Banco de Dados PostgreSQL (F1 2026 Mock Data)

DELETE FROM race_results;
DELETE FROM races;
DELETE FROM circuits;
DELETE FROM drivers;
DELETE FROM teams;

ALTER TABLE teams ALTER COLUMN id RESTART WITH 100;
ALTER TABLE drivers ALTER COLUMN id RESTART WITH 100;
ALTER TABLE circuits ALTER COLUMN id RESTART WITH 100;
ALTER TABLE races ALTER COLUMN id RESTART WITH 100;
ALTER TABLE race_results ALTER COLUMN id RESTART WITH 1000;

INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (1, 'Mercedes AMG', 'Germany', 'Brackley, UK', 'Mercedes');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (2, 'Scuderia Ferrari', 'Italy', 'Maranello, ITA', 'Ferrari');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (3, 'McLaren F1 Team', 'United Kingdom', 'Woking, UK', 'Mercedes');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (4, 'Red Bull Racing', 'Austria', 'Milton Keynes, UK', 'Honda RBPT');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (5, 'RB F1 Team', 'Italy', 'Faenza, ITA', 'Honda RBPT');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (6, 'Alpine', 'France', 'Enstone, UK', 'Renault');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (7, 'Haas', 'United States', 'Kannapolis, USA', 'Ferrari');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (8, 'Audi', 'Germany', 'Hinwil, SUI', 'Audi');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (9, 'Williams', 'United Kingdom', 'Grove, UK', 'Mercedes');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (10, 'Aston Martin', 'United Kingdom', 'Silverstone, UK', 'Mercedes');
INSERT INTO teams (id, name, country, base_location, power_unit) VALUES (11, 'Cadillac', 'United States', 'Fishers, USA', 'Cadillac');

INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (1, 'ANT', 12, 'Andrea Kimi', 'Antonelli', 'Italian', 1);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (2, 'RUS', 63, 'George', 'Russell', 'British', 1);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (3, 'HAM', 44, 'Lewis', 'Hamilton', 'British', 2);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (4, 'NOR', 4, 'Lando', 'Norris', 'British', 3);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (5, 'LEC', 16, 'Charles', 'Leclerc', 'Monegasque', 2);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (6, 'VER', 1, 'Max', 'Verstappen', 'Dutch', 4);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (7, 'PIA', 81, 'Oscar', 'Piastri', 'Australian', 3);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (8, 'HAD', 17, 'Isack', 'Hadjar', 'French', 4);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (9, 'LAW', 30, 'Liam', 'Lawson', 'New Zealander', 5);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (10, 'GAS', 10, 'Pierre', 'Gasly', 'French', 6);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (11, 'DOO', 7, 'Jack', 'Doohan', 'Australian', 6);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (12, 'TSU', 22, 'Yuki', 'Tsunoda', 'Japanese', 5);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (13, 'HUL', 27, 'Nico', 'Hülkenberg', 'German', 8);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (14, 'OCO', 31, 'Esteban', 'Ocon', 'French', 7);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (15, 'BEA', 87, 'Oliver', 'Bearman', 'British', 7);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (16, 'ALB', 23, 'Alexander', 'Albon', 'Thai', 9);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (17, 'SAI', 55, 'Carlos', 'Sainz', 'Spanish', 9);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (18, 'ALO', 14, 'Fernando', 'Alonso', 'Spanish', 10);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (19, 'BOR', 5, 'Gabriel', 'Bortoleto', 'Brazilian', 8);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (20, 'STR', 18, 'Lance', 'Stroll', 'Canadian', 10);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (21, 'HER', 26, 'Colton', 'Herta', 'American', 11);
INSERT INTO drivers (id, code, permanent_number, first_name, last_name, nationality, team_id) VALUES (22, 'OWA', 28, 'Pato', 'O''Ward', 'Mexican', 11);

INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (1, 'Albert Park', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (1, 2026, 1, 'Australian GP', '2026-03-08', 1, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (2, 'Shanghai', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (2, 2026, 2, 'Chinese GP', '2026-03-15', 2, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (3, 'Suzuka', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (3, 2026, 3, 'Japanese GP', '2026-03-29', 3, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (4, 'Miami', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (4, 2026, 4, 'Miami GP', '2026-05-03', 4, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (5, 'Montreal', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (5, 2026, 5, 'Canadian GP', '2026-05-24', 5, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (6, 'Monte Carlo', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (6, 2026, 6, 'Monaco GP', '2026-06-07', 6, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (7, 'Barcelona', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (7, 2026, 7, 'Spanish GP', '2026-06-14', 7, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (8, 'Red Bull Ring', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (8, 2026, 8, 'Austrian GP', '2026-06-28', 8, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (9, 'Silverstone', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (9, 2026, 9, 'British GP', '2026-07-05', 9, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (10, 'Spa-Francorchamps', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (10, 2026, 10, 'Belgian GP', '2026-07-19', 10, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (11, 'Hungaroring', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (11, 2026, 11, 'Hungarian GP', '2026-07-26', 11, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (12, 'Zandvoort', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (12, 2026, 12, 'Dutch GP', '2026-08-23', 12, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (13, 'Monza', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (13, 2026, 13, 'Italian GP', '2026-09-06', 13, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (14, 'Madrid', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (14, 2026, 14, 'Spanish GP (Madrid)', '2026-09-13', 14, true);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (15, 'Baku', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (15, 2026, 15, 'Azerbaijan GP', '2026-09-26', 15, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (16, 'Sepang', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (16, 2026, 16, 'Malaysia GP', '2026-10-04', 16, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (17, 'Marina Bay', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (17, 2026, 17, 'Singapore GP', '2026-10-11', 17, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (18, 'COTA', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (18, 2026, 18, 'United States GP', '2026-10-25', 18, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (19, 'Hermanos Rodríguez', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (19, 2026, 19, 'Mexico City GP', '2026-11-01', 19, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (20, 'Interlagos', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (20, 2026, 20, 'Brazilian GP', '2026-11-08', 20, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (21, 'Las Vegas Strip', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (21, 2026, 21, 'Las Vegas GP', '2026-11-22', 21, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (22, 'Losail', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (22, 2026, 22, 'Qatar GP', '2026-11-29', 22, false);
INSERT INTO circuits (id, name, location, country, length_km, laps) VALUES (23, 'Yas Marina', 'Unknown', 'Unknown', 5.0, 50);
INSERT INTO races (id, season, round, name, date, circuit_id, completed) VALUES (23, 2026, 23, 'Abu Dhabi GP', '2026-12-06', 23, false);

INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (1, 1, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (2, 2, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (3, 3, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (4, 4, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (5, 5, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (6, 6, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (7, 7, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (8, 8, 1, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (9, 9, 1, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (10, 10, 1, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (11, 11, 1, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (12, 12, 1, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (13, 13, 1, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (14, 14, 1, 9, 9, 2, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (15, 1, 2, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (16, 2, 2, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (17, 3, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (18, 4, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (19, 5, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (20, 6, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (21, 7, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (22, 8, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (23, 9, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (24, 10, 2, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (25, 11, 2, 3, 3, 15, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (26, 12, 2, 9, 9, 2, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (27, 1, 3, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (28, 2, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (29, 3, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (30, 4, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (31, 5, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (32, 6, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (33, 7, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (34, 8, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (35, 9, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (36, 10, 3, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (37, 11, 3, 8, 8, 4, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (38, 1, 4, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (39, 2, 4, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (40, 3, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (41, 4, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (42, 5, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (43, 6, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (44, 7, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (45, 8, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (46, 9, 4, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (47, 10, 4, 5, 5, 10, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (48, 1, 5, 1, 1, 25, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (49, 2, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (50, 3, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (51, 4, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (52, 5, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (53, 6, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (54, 7, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (55, 8, 5, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (56, 9, 5, 3, 3, 15, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (57, 10, 5, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (58, 1, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (59, 2, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (60, 3, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (61, 4, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (62, 5, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (63, 6, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (64, 7, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (65, 8, 6, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (66, 9, 6, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (67, 1, 7, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (68, 2, 7, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (69, 3, 7, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (70, 4, 7, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (71, 5, 7, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (72, 6, 7, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (73, 7, 7, 4, 4, 12, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (74, 1, 8, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (75, 2, 8, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (76, 3, 8, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (77, 4, 8, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (78, 5, 8, 4, 4, 12, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (79, 6, 8, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (80, 1, 9, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (81, 2, 9, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (82, 3, 9, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (83, 4, 9, 8, 8, 4, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (84, 5, 9, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (85, 1, 10, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (86, 2, 10, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (87, 3, 10, 8, 8, 4, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (88, 4, 10, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (89, 1, 11, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (90, 2, 11, 6, 6, 8, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (91, 3, 11, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (92, 1, 12, 2, 2, 18, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (93, 1, 13, 3, 3, 15, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (94, 1, 14, 4, 4, 12, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (95, 1, 15, 6, 6, 8, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (96, 2, 15, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (97, 1, 16, 6, 6, 8, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (98, 1, 17, 9, 9, 2, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (99, 2, 17, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (100, 1, 18, 9, 9, 2, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (101, 2, 18, 10, 10, 1, 'FINISHED', false);
INSERT INTO race_results (id, race_id, driver_id, position, grid_position, points, status, fastest_lap) VALUES (102, 1, 19, 9, 9, 2, 'FINISHED', false);
